name: Terraform Checks

on:
  pull_request:
    branches:
      - test-terraform-workflow  
  push:
    branches:
      - test-terraform-workflow  

jobs:
  terraform:
    name: Terraform Format & Validate
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5   

      
      - name: Run terraform fmt (auto-fix)
        run: terraform fmt -recursive

     
      - name: Commit formatting changes if any
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore: auto-format Terraform code" || echo "No changes to commit"
          git push origin HEAD:test-terraform-workflow

      
      - name: Terraform Init
        run: terraform init -backend=false

      
      - name: Terraform Validate
        run: terraform validate
