name: 'Terraform'

on:
  workflow_call:
    inputs:
      source-path:
        required: true
        type: string

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_github_token: ${{ secrets.CI_GITHUB_TOKEN }} # Required variable
      # Add other required TF_VAR_<variable_name> secrets here if needed
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.source-path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (with backend)
        run: terraform init -reconfigure

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
